networks:
  app-tier:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: dockerfile_app
    networks:
      - app-tier
    security_opt:
      - no-new-privileges:true
      - apparmor:unconfined
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres 
      - SPRING_DATASOURCE_USERNAME=myuser 
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=100MB
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=1000MB    
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-production}
    volumes:
        #bitnami image wants jar in /app
      - ./app/build/libs/app.jar:/app/s4-backend-1.0.0.jar
      - ./secrets/db_password.txt:/app/db_password.txt:ro
      - ./secrets/google_public_key.txt:/app/google_public_key.txt:ro
      - ./secrets/testkey.txt:/app/testkey.txt:ro
  
  db:
    image: bitnami/postgresql:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRESQL_USERNAME} -d $${POSTGRESQL_DATABASE}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - app-tier
    tty: true
    security_opt:
      - no-new-privileges:true
      - apparmor:unconfined
    #cap_drop: #causes fail currently
    #  - ALL
    #cap_add:
     # - NET_BIND_SERVICE
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=myuser  
      - POSTGRESQL_PASSWORD_FILE=/data/secrets/db_password.txt
      - POSTGRESQL_DATABASE=postgres
    volumes:
      - ./secrets/db_password.txt:/data/secrets/db_password.txt:ro


