services:
  app:
    build:
      context: .
      dockerfile: dockerfile_app
    security_opt:
      - no-new-privileges:true
      - apparmor:unconfined
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres 
      - SPRING_DATASOURCE_USERNAME=compose-postgres # these need to be replaced with a secret
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=100MB
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=100MB        
    secrets:
      - testkey 
  
  db:
    image: 'postgres:13.1-alpine'
    security_opt:
      - no-new-privileges:true
      - apparmor:unconfined
    #cap_drop: #causes fail currently
    #  - ALL
    #cap_add:
     # - NET_BIND_SERVICE
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=compose-postgres # these need to be replaced with a secret
      - POSTGRES_PASSWORD=compose-postgres

secrets:
  testkey: 
    file: secrets/testkey.txt